### ISSUE TITLE
Warning during Compile: Broken Library Manifest

### ISSUE THREAD

**Issue by lbussy** [RobTillaart/DS18B20_RT#1]
Hi Rob,

Compiling one of the test scripts and I'm getting the following warning:

```
Warning! Ignoring broken library manifest in C:\Users\xxxxxxxx\xxxxxxxx\Documents\PlatformIO\Projects\Test OneWire\.pio\libdeps\lolin_d32\DS18B20_RT_ID7227
```

I am using PLatformIO's library manager on VSCode (Windows of course.)

**Comment by RobTillaart** [comment]
Not worked with platformIO myself, i need to check the specs.

Will dive into it this week.

**Comment by RobTillaart** [comment]
had a quick look:
1) can you post the contents of the library.json file?

I see that https://platformio.org/lib/show/7227/DS18B20_RT/manifest
gives the wrong content - it shows library.properties instead of the library.json

https://platformio.org/lib/show/5544/DS18B20/manifest - shows library.json

**Comment by RobTillaart** [comment]
Found a problem in the json file 
```
    "url": "https://github.com/RobTillaart/DS18B20
```
misses end quotes. The json was invalid.

**Comment by RobTillaart** [comment]
0.1.3 released, if the warning still appears please reopen the issue

**Comment by lbussy** [comment]
Confirmed fixed when addressing via GitHub link.  It seems to take the Arduino and PlatformIO repos some time to get the new version.
