### ISSUE TITLE
Loose data wire causes CRC error, but fixing the connection doesn't fix the CRC error until the microcontroller is reset

### ISSUE THREAD

**Issue by melyux** [RobTillaart/DS18B20_RT#11]
If I, for example, unplug the data wire, the DS18B20 will start returning CRC errors. Even if I fix the physical connection, it continues to return the CRC error value. It only goes back to normal if I reset the microcontroller.

Is there something we can call to try to reset the DS18B20 connection upon CRC errors without having to reset the whole microcontroller?

**Comment by RobTillaart** [comment]
Think you need to do a **oneWire.reset()** as oneWire lib is the core of the communication.
(No things nearby to check it)

**Comment by melyux** [comment]
Great! It worked. I used this, which worked in resetting the connection and getting it back to normal:
```cpp
if (!sensor.begin()) {
    oneWire.reset();
    sensor.begin();
}
```

Maybe you could add it to the README or as an example of how to recover from those errors. In fact, one should probably call `sensor.begin()` before any non-emergency reading, otherwise `sensor.requestTemperatures()` and `sensor.getTempC()` will continue working even if the sensor is disconnected (returning a reading of 0°C), and you wouldn't know unless you ran `sensor.begin()`.

**Comment by RobTillaart** [comment]
Then it would be better to add the call to **reset()** inside ""begin()** call (in the retry loop ..see .cpp). 
Maybe other places too?

Thinking of adding he retry count as parameter to **begin(retry = 3)** or a delay to give it more time to check connection?

**Comment by RobTillaart** [comment]
added **oneWire.reset()** in **begin()**.
So one can just call **sensor.begin()** after a disconnect, no need to "dive into lower layers"

user can call **begin()** in a loop with a timeout (or not), something like 

```cpp
uint32_t start = millis():
bool success = false;
while ( millis() - start < 3000) 
{
  success = sensor.begin();
  if (success) break;
}
if (!success) ...
```

If this does not solve the problem, please reopen the issue.
