### ISSUE TITLE
First sensor fails in example sketch

### ISSUE THREAD

**Issue by lbussy** [RobTillaart/DS18B20_RT#2]
Hi Rob:

I have noticed that the first sensor access always returns a fault condition.  Taking your [two-sensor sketch](https://github.com/RobTillaart/DS18B20_RT/blob/master/examples/DS18B20_two_sensors/DS18B20_two_sensors.ino) as an example, the first sensor fails consistently:

```
src\main.cpp
DS18B20 Library version: 0.1.2
inside: -0.1
outside:                22.3
inside: -0.1
outside:                22.3
inside: -0.1
outside:                22.3
...
```

However, if I do the DS18B20::begin() twice for the first sensor, it all seems to work

``` cpp
    inside.begin();
    inside.begin();
    outside.begin();
```

It's obviously an easy work-around, but something seems strange.

**Comment by RobTillaart** [comment]
Will dive into this asap

**Comment by lbussy** [comment]
Since you mentioned not using PlatformIO in the other issue, I tried this with the Arduino IDE:

```
DS18B20 Library version: 0.1.2
inside:	-0.1
outside:		22.0
inside:	-0.1
outside:		22.0
inside:	-0.1
```

Strangely, and possibly a clue, I did it first with no delay in the loop.  This was my result:

```
DS18B20 Library version: 0.1.2
outside:		21.8
outside:		21.8
outside:		21.8
inside:	-0.1
outside:		21.8
outside:		21.8
outside:		21.8
outside:		21.8
inside:	-0.1
outside:		21.8
outside:		21.8
outside:		21.8
outside:		21.8
inside:	-0.1
outside:		21.8
outside:		21.8
outside:		21.8
outside:		21.8
inside:	-0.1
```

Of note, the failing sensor did not attempt to print out the first pass through, and then subsequently took ~4X longer to convert.

**Comment by RobTillaart** [comment]
I see the inside sensor failing on every call. 
Can you swap the sensors (or the pin in software) to exclude hardware cause?
Do you have appropriate pull up resistors?

**Comment by RobTillaart** [comment]
I build a breadboard with 2 sensors both with 4K7 pull up resistor. 
IDE 1.8.12   UNO   
code just worked so I cannot recreate your bug.

So please redo the wiring, check each sensor standalone to be sure your sensor is OK.

**Comment by lbussy** [comment]
This is on a Wemos Lolin D32.  I have five sensors on the breadboard, each with a dedicated pull-up resistor, and I can reproduce this no matter which pin is first.

Test code:

``` cpp
#include "main.h"

OneWire oneWire1(SENSOR1);
OneWire oneWire2(SENSOR2);

DS18B20 inside(&oneWire1);
DS18B20 outside(&oneWire2);

void setup()
{
    setSerial();
    // inside.begin();
    inside.begin();
    outside.begin();
    inside.setResolution(12);
    outside.setResolution(12);
}

void loop()
{
    inside.requestTemperatures();
    outside.requestTemperatures();
    _delay(1000);

    if (inside.isConversionComplete())
        Log.verbose(F("Inside: Pin %l = %D°C" CR), SENSOR1, inside.getTempC(), 2);
    if (outside.isConversionComplete())
        Log.verbose(F("Outside: Pin %l = %D°C" CR), SENSOR2, outside.getTempC(), 2);
}
```

Run 1:

```
      3059 N: Serial logging started at 115200.
      4110 V: Inside: Pin 26 = -0.06°C
      4120 V: Outside: Pin 25 = 20.94°C
      5133 V: Inside: Pin 26 = -0.06°C
      5143 V: Outside: Pin 25 = 20.94°C
      6156 V: Inside: Pin 26 = -0.06°C
      6166 V: Outside: Pin 25 = 20.94°C
```

Swap pins for test 2:

```
      3059 N: Serial logging started at 115200.
      4110 V: Inside: Pin 25 = -0.06°C
      4120 V: Outside: Pin 26 = 20.75°C
      5133 V: Inside: Pin 25 = -0.06°C
      5143 V: Outside: Pin 26 = 20.81°C
      6156 V: Inside: Pin 25 = -0.06°C
      6166 V: Outside: Pin 26 = 20.81°C
```

Uncomment the first (extra) `DS18B20::begin()`:

```
      3059 N: Serial logging started at 115200.
      4126 V: Inside: Pin 26 = 20.75°C
      4135 V: Outside: Pin 25 = 20.94°C
      5149 V: Inside: Pin 26 = 20.81°C
      5158 V: Outside: Pin 25 = 20.94°C
      6172 V: Inside: Pin 26 = 20.81°C
      6181 V: Outside: Pin 25 = 20.94°C
```

Swap pins, still using the extra `DS18B20::begin()`:

```
      3059 N: Serial logging started at 115200.
      4126 V: Inside: Pin 25 = 20.94°C
      4135 V: Outside: Pin 26 = 20.75°C
      5149 V: Inside: Pin 25 = 20.94°C
      5158 V: Outside: Pin 26 = 20.75°C
      6172 V: Inside: Pin 25 = 20.94°C
      6181 V: Outside: Pin 26 = 20.75°C
```

Here I added a third pin upon which I execute the `DS18B20::begin()` but I do not reference it thereafter:

``` cpp
OneWire oneWire3(SENSOR3);
OneWire oneWire1(SENSOR1);
OneWire oneWire2(SENSOR2);

DS18B20 test(&oneWire3);
DS18B20 inside(&oneWire1);
DS18B20 outside(&oneWire2);

void setup()
{
    setSerial();
    test.begin();
```

You can see the results are the same:

```
      3059 N: Serial logging started at 115200.
      4126 V: Inside: Pin 25 = 21.00°C
      4135 V: Outside: Pin 26 = 20.81°C
      5149 V: Inside: Pin 25 = 21.00°C
      5158 V: Outside: Pin 26 = 20.81°C
      6172 V: Inside: Pin 25 = 21.00°C
      6181 V: Outside: Pin 26 = 20.81°C
```

My results are the same in the Arduino IDE.  I do have an Uno here somewhere.  I'll try on it and report back.

**Comment by RobTillaart** [comment]
The Wemos a 3.3V device, so the extra begin might just give the sensor some extra time.

What is the size of the pull up you're using?

You might try to reduce the pull ups resistor. In the Dallas Temperature Library we had a discussion about the size of the pull up R versus operating voltage and wire length.

**Comment by lbussy** [comment]
Yes sir - using 2.2K pullups.

I've tried with a delay in lieu of the extra begin, no difference.  I actually have a 3000ms delay at the start of that sketch where it sets up serial.

**Comment by RobTillaart** [comment]
I'm gonna find myself an esp32 board and try to recreate the problem.
Als my class is a wrapper around 1wire
- which version of 1wire do you use?

If you use e.g. the performance example there is no problem?

**Comment by lbussy** [comment]
I am using [Paul Stoffgren's OneWire](https://github.com/PaulStoffregen/OneWire).

I'll try some of the other examples as well.

**Comment by RobTillaart** [comment]
That's a very good one, but which version

At the end of the compilation you should see something like
```
Using library OneWire at version 2.3.5 in folder: D:\Rob\WORK\Arduino\libraries\OneWire 
Using library DS18B20 at version 0.1.3 in folder: D:\Rob\WORK\Arduino\libraries\DS18B20
```

**Comment by lbussy** [comment]
Sorry - OneWire version 2.3.5.

**Comment by RobTillaart** [comment]
Good test, 
With the extra begin, what are the timings?
The expected.values should be 90% or less.

**Comment by RobTillaart** [comment]
When you have one begin
And you press the reset button does it still fail?

**Comment by lbussy** [comment]
When I reset with a single begin there is no change.

When I do performance with two begin statements I get the following:

```
est takes about 30 seconds for 4 resolutions
RES	TIME	ACTUAL	GAIN	TEMP
9	94.00	87.00	92.6%	23.00
10	188.00	162.70	86.5%	22.75
11	375.00	313.85	83.7%	22.62
12	750.00	616.35	82.2%	22.56
```

**Comment by RobTillaart** [comment]
OK, that looks good and consistent with my UNO data.

So thus-far we have a problem with one sensor (the first)  on a wemos platform.
One call to begin() is not enough, a second call to same begin() fixes the problem,
In fact that could explain why sensor2,3,4,5 do work as supposed.

Sounds still like a timing problem to me, maybe it is an effect of setSerial() so lets give that some time.

(next step is to measure the timing of the calls to begin() to see if there are substantial differences in the calls, assumption is that they should be quite similar as only one sensor per pin is connected)

```
void setup()
{
    setSerial();
    delay(100);  // <<<<<<<
    test.begin();
    inside.begin();
    outside.begin();
...
```

Found an ESP32 WROOM, and some sensors so I'll be back soon.

**Comment by lbussy** [comment]
`setSerial()` is just part of my "local library" which I use for all of my sketches as a starting point.  For the tests I did in Arduino IDE, I used them verbatim without that function.

**Comment by RobTillaart** [comment]
Ok have ESP up and running. (its not a Wemos ...)

observations:
Connected 2 sensors to pin 2 and 4
Need to disconnect the sensors otherwise upload fails.
When reconnect the sensors start spitting out -0.1 as soon as I connect them.
Pressing reset button restarts and I get nice figures (~23.6 on both sensors.)

I notice that in my code I print some strings before I call the **begin()**
So lets try it without printing anything,

**Comment by lbussy** [comment]
I think 2 is the LED and 4 is SDA.  [This](https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/) is a pretty good reference for "safe" pins.

**Comment by RobTillaart** [comment]
That the code spits out -0.1 is understandable as begin() is executed before anything is connected.

With out the print statement. same behavior.
[lets think]

**Comment by RobTillaart** [comment]
Changed in the two sensor sketch
```
uint32_t start, d1, d2;

void setup(void)
{
  Serial.begin(115200);

  start = micros();
  inside.begin();
  d1 = micros()- start;

  start = micros();
  outside.begin();
  d2 = micros() - start;

  Serial.println(d1);
  Serial.println(d2);
...
```
JUst to get the timing of the two calls to **begin()**
These times are pretty identical, the first slightly larger
15966
15839
some variations, but the first call is always a ~100 microseconds slower.

Can you test this on the wemos?

**Comment by RobTillaart** [comment]
When I do second call to inside.begin() and measure that timing, the timings are more equal
15845
15854
A diff of only 9 micros, while it is doing essentially the same.

we're closing in.

**Comment by RobTillaart** [comment]
**begin()** returns a boolean when it finds a correct address.

so can you change the setup to:
```
void setup()
{
    setSerial();
    while (test.begin() == false);;
    while (inside.begin() == false);;
    while (outside.begin() == false);;
...
```

**Comment by lbussy** [comment]
That does address the issue somewhat more glamorously than the separate `begin()` call.  Seems to work fine in my test sketch.

**Comment by RobTillaart** [comment]
OK then I will embed this while loop inside the **begin()** call and add a #retries to make it robust.
Will take an hour or two as I am in a meeting now.

**Comment by RobTillaart** [comment]
Added fix, can you confirm it works?
you should now only call one time **begin()**

**Comment by lbussy** [comment]
Confirmed working, sir.  Thank you so much!
