### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by breitsi** [RobTillaart/DS18B20_RT#22]
There ist an Infinite loop in
DS18B20.cpp::begin()
If isConnected(retries) find a connection, setResolution() is called. At the Ende of setResolution() you call begin() again.

**Comment by RobTillaart** [comment]
Thanks for the issue. I will look at it asap as it sounds like a bug.

**Comment by RobTillaart** [comment]
A quick look confirms (99% sure) it came in with the latest PR / release. Apparently I did not test it good enough. Too late here to start now will try to come up with fix tomorrow.

**Comment by RobTillaart** [comment]
Thanks for the PR, it looked good so I merged it into the master branch.
