### ISSUE TITLE
read temperature using sensor address

### ISSUE THREAD

**Issue by rozrabiak** [RobTillaart/DS18B20_RT#26]
Is it possible?
For eg.  sensor.getTempC(SENSOR_ADDRESS);
I can't find in documentation.

**Comment by RobTillaart** [comment]
Thanks for the question.
Will check for an answer later (almost diner time here)

**Comment by RobTillaart** [comment]
First this library does not support the call as you propose.
This library uses the paradigm of **one sensor per IO pin** so you don't need to use any address.
You always know e.g. that inside is pin4 and outside is pin5, even after replacing sensors your sketch will just work.

That said, under the hood it uses an address, the first address it finds with 
```cpp
bool isConnected(uint8_t retries);
```

The question is:  what do you expect the function call you propose should do?

#### possible scenario's
So one could pretty easy implement an
```cpp
float getTempC(SENSOR_ADDRESS)
{
  if (SENSOR_ADDRESS != internal address) return -127;  //  typical error code for the DS18B20
  return getTempC();
}
```

or

```cpp
float getTempC(SENSOR_ADDRESS)
{
  internal address = SENSOR_ADDRESS;
  return getTempC();
}
```

Two straightforward implementationd that differ a lot in behavior.

**Comment by RobTillaart** [comment]
@rozrabiak 

Q: The question is: what do you expect the function call you propose should do?

**Comment by RobTillaart** [comment]
As there is no answer on my question, I close this issue.
