### ISSUE TITLE
DS18B20_LIB_VERSION was not declared and sensor.begin is not in class

### ISSUE THREAD

**Issue by LtHoangTran** [RobTillaart/DS18B20_RT#7]
Within the file DS18B20_simple.ino (gained upon from downloading the whole DS18B20_RT library from Library management in Arduino), I run the script and find myself with 2 troubles:

- The DS18B20_LIB_VERSION is not declared (I comment out this line, and the Serial.print(__FILE__), because this is in set up and relatively unimportant
- The sensor.begin() line is then shown with "exit status 1: 'class DS18B20' has no member named 'begin'"

**Comment by RobTillaart** [comment]
To recreate the problem,
- which platform are you using? 
- development environment.

**Comment by RobTillaart** [comment]
Tried to compile the mentioned example with UNO and ESP32 under IDE 1.8.12 and both platforms (boards) compile 100%.

So I cannot recreate.

> The DS18B20_LIB_VERSION is not declared 
- The lines you commented out are indeed not important. I add them as they help to see which code /lib version is in a chip. The message it is not declared has the same cause as the **begin()** error. Class cannot be found?

> The sensor.begin() line is then shown with "exit status 1: 'class DS18B20' has no member named 'begin'"

Are there more error messages during compile?

Do you have verbose compiling?  MENU->FILE->PREFERENCES

**Comment by LtHoangTran** [comment]
> To recreate the problem,
> 
> * which platform are you using?
> * development environment.

I'm using Arduino IDE (latest version) on Windows 10
Platform includes: Arduino Mega 2560 (or at least, a clone version), DS18B20 temperature (waterproof version). I have a separate ESP32, but I haven't incorporated it in my project (yet).

> Are there more error messages during compile?

I'm copy-paste the whole chunk of error reports here:

C:\Users\admin\AppData\Local\Temp\arduino_modified_sketch_968967\DS18B20_simple.ino: In function 'void setup()':
DS18B20_simple:26:10: error: 'class DS18B20' has no member named 'begin'
   sensor.begin();
          ^~~~~
C:\Users\admin\AppData\Local\Temp\arduino_modified_sketch_968967\DS18B20_simple.ino: In function 'void loop()':
DS18B20_simple:32:10: error: 'class DS18B20' has no member named 'requestTemperatures'
   sensor.requestTemperatures();
          ^~~~~~~~~~~~~~~~~~~
DS18B20_simple:34:18: error: 'class DS18B20' has no member named 'isConversionComplete'; did you mean 'doConversion'?
   while (!sensor.isConversionComplete());  // wait until sensor is ready
                  ^~~~~~~~~~~~~~~~~~~~
                  doConversion
Multiple libraries were found for "DS18B20.h"
 Used: C:\Users\admin\Documents\Arduino\libraries\DS18B20
 Not used: C:\Users\admin\Documents\Arduino\libraries\MaximWire
 Not used: C:\Users\admin\Documents\Arduino\libraries\DS18B20_RT
 Not used: C:\Users\admin\Documents\Arduino\libraries\OneWireHub
Using library OneWire-master at version 2.3.5 in folder: C:\Program Files (x86)\Arduino\libraries\OneWire-master 
Using library DS18B20 at version 1.0.0 in folder: C:\Users\admin\Documents\Arduino\libraries\DS18B20 
exit status 1
'class DS18B20' has no member named 'begin'

**Comment by RobTillaart** [comment]
The cause is explained in your error log.

**Not used: C:\Users\admin\Documents\Arduino\libraries\DS18B20_RT**

You should rename / move the libraries that interfere.
If the problem still occurs please reopen the isssue
